FROM golang:1.22 AS builder
ARG COMPONENT
WORKDIR /workspace
COPY . .
RUN go build -o app ./cmd/$COMPONENT

FROM debian:latest
RUN \
 apt-get update && \
 apt-get install -y --no-install-recommends ca-certificates curl vim && \
 rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
COPY --from=builder /workspace/app .
CMD ["./app"]
